version: "3.8"

services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-instance
    ports:
      - "1337:1337"
      - "22:22"
    restart: unless-stopped
